FROM php:8.1-fpm-alpine3.16

RUN apk add --no-cache \
    git \
    zlib-dev \
    libxml2-dev \
    libzip-dev \
    icu-dev \
    && docker-php-ext-install zip intl mysqli pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY ./ /var/www/donut
WORKDIR /var/www/donut/

EXPOSE 9000
